# Generated by Django 4.2.3 on 2023-09-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='role',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='category',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscription_category', to='newsletter.category'),
        ),
    ]
