# Generated by Django 4.2.3 on 2023-09-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_rename_article_category_articles_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='category',
        ),
    ]
