# Generated by Django 4.2.3 on 2023-09-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_articles_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='user',
        ),
        migrations.DeleteModel(
            name='articles',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='subscriptions',
        ),
    ]
